<script lang="ts">
  export let data;
</script>

{#if data.slug === "long"}
<p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita dolorem libero perferendis perspiciatis odio atque amet tenetur, repellat non debitis. A repudiandae consequatur eaque? Quas praesentium magnam ad voluptatum esse!</span><span>Totam facere tempore ab, voluptatibus accusamus exercitationem iusto recusandae quos dicta eveniet corrupti eum quas placeat, saepe vel error itaque a. Facere atque aspernatur, perspiciatis modi provident consequuntur neque ab?</span><span>Numquam rem consequatur, nostrum veniam quia, ad soluta inventore totam asperiores, optio odio necessitatibus dolores cumque non ullam in iste tempora consequuntur minus debitis recusandae! Voluptas ea distinctio molestiae suscipit!</span></p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque, labore pariatur maxime tempore ea eligendi vero sapiente ut saepe recusandae quisquam fuga minus iure dolorem mollitia obcaecati, nostrum officia placeat?</span><span>Blanditiis, inventore impedit nisi voluptatem hic culpa expedita, magnam ducimus aspernatur odit omnis dolor debitis cupiditate, iste laudantium enim cumque eligendi optio voluptate facilis tempore distinctio iure maxime? Quas, obcaecati.</span><span>Quae officiis provident ratione quibusdam eveniet mollitia, vero debitis quam facere eum illum dolorum unde ut dolor sit. Dolor magni ea distinctio consequuntur aut sed voluptas iusto voluptates sit vitae?</span></p>
<p><span>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi corrupti asperiores molestias, molestiae accusamus aspernatur necessitatibus et dolor id blanditiis quam mollitia, laboriosam totam laudantium sed doloribus deleniti ut voluptate!</span><span>Enim eius culpa doloribus nulla, obcaecati sit consequuntur nisi. Recusandae pariatur inventore eum veritatis odio? Animi optio pariatur, ab ipsa quisquam qui odit obcaecati rem eum voluptatibus quis distinctio explicabo!</span><span>Hic laboriosam obcaecati nisi in ea ratione, eveniet sint quis error et voluptatem quo iusto provident! Veritatis porro molestiae, nisi expedita quo quidem exercitationem quia. Ipsa cum fugiat distinctio eligendi.</span></p>
<p><span>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repudiandae ab tempora rerum nemo doloremque quidem debitis vitae ea architecto adipisci, porro qui error, esse quod repellat quasi et ipsum maxime.</span><span>Veniam quo quibusdam tempore similique necessitatibus. Excepturi inventore aliquam velit amet sint ut pariatur, nesciunt doloribus nostrum? Harum, voluptatum placeat animi ratione est et quidem reiciendis voluptate officiis corporis qui.</span><span>Delectus eius vitae esse non? Reiciendis amet eligendi, porro odit facilis magnam laboriosam quis explicabo deleniti asperiores impedit libero, consequuntur, odio eveniet officiis excepturi accusamus? Labore dolore id tempora nisi.</span></p>
<p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem corrupti vitae nostrum odit beatae nulla magnam autem at, reprehenderit minus tempora aut aperiam officia excepturi deleniti blanditiis similique, dicta fuga!</span><span>Dolorum eum ut nemo, iusto error voluptatibus, magni perferendis inventore expedita, eaque aperiam at asperiores perspiciatis enim praesentium culpa optio blanditiis quia consequuntur assumenda quas harum quis nobis. Dolores, culpa.</span><span>Ex quia consequatur modi quos omnis harum aperiam labore, voluptatum molestias? Hic itaque quod cupiditate sequi laudantium inventore tempore assumenda deserunt atque quidem ut exercitationem, consequatur ad reprehenderit ea praesentium.</span></p>
<p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat temporibus consequatur tenetur laborum maxime iusto cum ut ex nihil neque vitae animi vero hic, nisi sed voluptate nobis, dicta nam.</span><span>Qui quibusdam laborum dignissimos molestias impedit inventore excepturi, magni molestiae minus, asperiores laboriosam hic error quis, soluta a maxime! Eaque voluptatem corporis exercitationem. Perspiciatis voluptatem voluptatibus amet iure omnis! Libero!</span><span>Fugiat facilis et saepe molestiae, earum, in unde architecto ducimus eligendi alias ea! Minus eveniet sunt perferendis rem qui a facere odit sit. Deserunt iusto, architecto et enim iste distinctio.</span></p>
<p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore quasi, voluptatem unde pariatur laboriosam beatae deserunt! Eos similique voluptate, esse, quasi dolores temporibus maiores error provident, at porro ipsum dolore?</span><span>Ipsam quis, illo exercitationem maiores repudiandae, est nam sed numquam error cupiditate, maxime ex id. Illum nisi et quos, dolor culpa reiciendis incidunt exercitationem, nobis, consectetur delectus dignissimos doloremque fuga.</span><span>Assumenda est tempora hic aut perspiciatis id enim nostrum rem? Voluptatem esse est optio itaque accusamus! Esse error officia sed dolor in numquam, ducimus ratione, reiciendis nihil, neque quaerat delectus?</span></p>
<p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita, magni. Officia vitae aliquid qui ratione quae? Assumenda qui dolores vel eum minus sit in tempore hic, dolorum exercitationem optio omnis!</span><span>Autem voluptatibus quos neque labore ab maxime libero soluta ipsa hic aliquam id quae culpa pariatur deserunt, nostrum tempora perferendis! Culpa ullam neque animi, unde adipisci itaque reprehenderit temporibus voluptas?</span><span>Excepturi cupiditate dolores quia nulla a repudiandae est minima, veritatis voluptatem magnam aliquid odio, tempora illum debitis quod, repellat blanditiis pariatur? Quis laboriosam tempore deserunt beatae fugiat est, molestiae rerum?</span></p>
<p><span>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam cum eum dolorum facilis itaque beatae autem qui molestiae expedita illum adipisci quo officiis unde libero mollitia neque quas, ducimus excepturi!</span><span>Recusandae voluptate a temporibus rem omnis, quis harum dolore eaque ducimus quam, alias doloremque magni sunt iste sed asperiores expedita mollitia voluptatum enim illum eligendi laudantium quo placeat cumque. Soluta.</span><span>Reiciendis eius facilis ullam, dolor quis laboriosam voluptatem earum. At earum, odio autem ex voluptate iusto iste sequi animi saepe reiciendis vel sed asperiores blanditiis tempora, alias expedita architecto? Et.</span></p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsum natus a et eum rerum vero incidunt recusandae cupiditate, magni aliquam fuga alias vel totam ab assumenda? Vitae mollitia tempora rem?</span><span>Delectus pariatur praesentium, mollitia non commodi veniam, at officiis aliquam similique dignissimos accusantium dolor rem aspernatur. Incidunt, exercitationem? Tenetur vel ratione at ad illo repudiandae nulla, quo iusto voluptatibus impedit.</span><span>Nesciunt illo a placeat vitae, saepe eligendi itaque! Hic in autem, tempora exercitationem quis illo! Aut eius alias quibusdam labore delectus est voluptate, explicabo corporis, sed harum sint rem eveniet.</span></p>
{:else}
{data.slug}
{/if}
